// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnZ2cp9mpBgBzNl0JqfmYyyTN3xXN7cKg',
    appId: '1:276637768261:web:4edddb696189af0d02e12c',
    messagingSenderId: '276637768261',
    projectId: 'fir-347b1',
    authDomain: 'fir-347b1.firebaseapp.com',
    storageBucket: 'fir-347b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLGlquyFGvyiUGwDCSrzoyF1J1uORqQuA',
    appId: '1:276637768261:android:b120bc5cf69663ff02e12c',
    messagingSenderId: '276637768261',
    projectId: 'fir-347b1',
    storageBucket: 'fir-347b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbOen_iIqlRh7hrzvO21mq4kBEKFi1JuU',
    appId: '1:276637768261:ios:1f123fec40bfb4e702e12c',
    messagingSenderId: '276637768261',
    projectId: 'fir-347b1',
    storageBucket: 'fir-347b1.appspot.com',
    iosBundleId: 'com.example.flutterDynamicWidget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbOen_iIqlRh7hrzvO21mq4kBEKFi1JuU',
    appId: '1:276637768261:ios:1f123fec40bfb4e702e12c',
    messagingSenderId: '276637768261',
    projectId: 'fir-347b1',
    storageBucket: 'fir-347b1.appspot.com',
    iosBundleId: 'com.example.flutterDynamicWidget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnZ2cp9mpBgBzNl0JqfmYyyTN3xXN7cKg',
    appId: '1:276637768261:web:03a8e9f856dc8eca02e12c',
    messagingSenderId: '276637768261',
    projectId: 'fir-347b1',
    authDomain: 'fir-347b1.firebaseapp.com',
    storageBucket: 'fir-347b1.appspot.com',
  );
}
